# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: migrazione-git-azure-devops

builds:
  - id: migrazione-git-azure-devops
    main: ./cmd/migrazione-git-azure-devops
    binary: migrazione-git-azure-devops_{{ .Os }}_{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: migrazione-git-azure-devops-windows
    main: ./cmd/migrazione-git-azure-devops
    binary: migrazione-git-azure-devops_{{ .Os }}_{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    hooks:
      pre:
        - cmd: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
        - cmd: goversioninfo
            -product-version {{.Version}}
            -file-version {{.Version}}
            -ver-major {{.Major}}
            -ver-minor {{.Minor}}
            -ver-patch {{.Patch}}
            -ver-build 0
            -product-name "migrazione-git-azure-devops"
            -company "Antonio Musarra's Blog"
            -description "Migrazione repository Git tra progetti Azure DevOps"
            -copyright "Copyright (c) 2025 Antonio Musarra\'s Blog"
            -icon ./cmd/migrazione-git-azure-devops/metadata/logo_32x32.ico
            -o ./cmd/migrazione-git-azure-devops/versioninfo_windows.syso
            ./cmd/migrazione-git-azure-devops/metadata/versioninfo.json
      post:
        - cmd: rm -f ./cmd/migrazione-git-azure-devops/versioninfo_windows.syso        

archives:
  - id: archive
    ids:
      - migrazione-git-azure-devops
      - migrazione-git-azure-devops-windows
    formats: [tar.gz]
    files:
      - LICENSE
      - README.md
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: amusarra
    name: migrazione-git-azure-devops
  draft: false
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
    Antonio Musarra's Blog - [https://www.dontesta.it](https://www.dontesta.it)
