name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # per lanciarlo manualmente

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessario per changelog

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --timeout=5m

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: ~> v2
          args: release --clean --snapshot --skip=publish,docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: migrazione-git-azure-devops-artifacts-${{ github.run_number }}
          path: dist/**
          if-no-files-found: error
          retention-days: 14