name: Go Release

permissions:
  contents: write
  packages: write
on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*"  # include pre-release tags

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codice
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessario per changelog

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v6.4.0
        with:
          version: ~> v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}